External Link Module Behat test
SU-SWS/linky_clicky pull request #214
Opened 2019-03-29 01:50 UTC by cjwest

#  READY FOR REVIEW

# Summary
These are behat tests for the external link module

# Needed By (Date)
- Soon. It's needed to put the External Link module on SRWC

# Urgency
- Important for us to go forward putting the External Link module on SRWC

# Steps to Test

I added a "Local" site to make it easier to test
Navigate to `linky_clicky/sites/local`
Create your behat.local.yml file
Run the External Link behat tests
`../../bin/behat -s dev -p local-local features/drupal.org/extlink/extlink.feature`

# Affected Projects or Products
- Needed for the SRWC site

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/LBRESRWC-74
- This may be a mistake. These Behat tests rely on the _Stanford Landing Page_ module. This was because I that's how they want to use it on the SRWC site. 
- Anyone who should be notified? (`@mention` them here)
@alisonho 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2019-04-02 22:27 UTC, jbickar commented
You don't need the `composer.lock` changes nor the image file that you included (you're not using the image file in the Feature).

2019-04-02 23:41 UTC, jbickar requested changes
Feature looks good to me. Please revert the `composer.lock` changes and remove the extraneous image at `includes/features/drupal.org/extlink/img/ooooaaaahhh.jpg` and then this is GTG.

Thanks - nice work!

2019-04-19 22:03 UTC, cjwest commented
@jbickar,
Ready to merge! (I hope :)

2019-04-22 20:28 UTC, jbickar approved these changes

2019-04-22 20:29 UTC, merged